@startuml
skinparam classAttributeIconSize 0
class 学生 {
 -学生ID
 -名前
 -生年月日
 -専門分野
 -入学年度
 -卒業年月日
 +入学する()
 +専門分野を決める()
 +卒業する()
}

' class 学生オブジェクト{
'  -学生ID:112233
'  -名前:田中太郎
'  -生年月日:19880601
'  -専門分野:セキュリティ
'  -入学年度:20040401
'  -卒業年月日:19860707
'  +入学する()
'  +専門分野を決める()
'  +卒業する()
' }
@enduml
