@startuml
class 図書 {
  +図書ID : int
  +書名 : string
  +著者 : string
  +種類 : string  <<書籍/雑誌>>
  +在庫状況 : string  <<貸出中/在庫あり>>
}

class 利用者 {
  +会員番号 : string
  +氏名 : string
  +所属 : string <<学生/教職員>>
  +メールアドレス
}

class 貸出 {
  +貸出日 : date
  +返却予定日 : date
}

class 予約 {
  +予約日 : date
  +予約ステータス : string <<待機中/完了>>
}

class 貸出履歴 {
  +貸出日 : date
  +返却日 : date
}

利用者 "1" -- "0..*" 貸出
図書 "1" -- "0..*" 貸出
利用者 "1" -- "0..*" 予約
図書 "1" -- "0..*" 予約
図書 "1" -- "0..*" 貸出履歴
利用者 "1" -- "0..*" 貸出履歴
@enduml
