@startuml
skinparam componentStyle rectangle

[図書] o-- [図書ID]
[図書] o-- [書名]
[図書] o-- [著者]
[図書] o-- [種類]      
[図書] o-- [状態]      

[利用者] o-- [会員番号]
[利用者] o-- [氏名]
[利用者] o-- [種別]
[利用者] o-- [メールアドレス]   
[利用者] o-- [予約カード]
[予約カード] o-- [書名]

[貸出] o-- [貸出ID]
[貸出] o-- [貸出日]
[貸出] o-- [返却予定日]

[予約] o-- [予約ID]
[予約] o-- [予約日]
[予約] o-- [予約ステータス]

[貸出履歴] o-- [履歴ID]
[貸出履歴] o-- [貸出日]
[貸出履歴] o-- [返却日]

' 関連
[利用者] o-- [貸出]
[図書] o-- [貸出]
[利用者] o-- [予約]
[図書] o-- [予約]
[図書] o-- [貸出履歴]
[利用者] o-- [貸出履歴]

@enduml
